import AccountantJson from "../artifacts/contracts/core/AccountantProviders.sol/AccountantProviders.json";
import type { AccountantProviders$Type } from "../artifacts/contracts/core/AccountantProviders.sol/artifacts.d.ts";
import BoringVaultJson from "../artifacts/contracts/core/BoringVault.sol/BoringVault.json";
import type { BoringVault$Type } from "../artifacts/contracts/core/BoringVault.sol/artifacts.d.ts";
import WithdrawerJson from "../artifacts/contracts/core/DelayedWithdraw.sol/DelayedWithdraw.json";
import type { DelayedWithdraw$Type } from "../artifacts/contracts/core/DelayedWithdraw.sol/artifacts.d.ts";
import DistributorJson from "../artifacts/contracts/core/Distributor.sol/Distributor.json";
import type { Distributor$Type } from "../artifacts/contracts/core/Distributor.sol/artifacts.d.ts";
import ManagerJson from "../artifacts/contracts/core/ManagerWithMerkleVerification.sol/ManagerWithMerkleVerification.json";
import type { ManagerWithMerkleVerification$Type } from "../artifacts/contracts/core/ManagerWithMerkleVerification.sol/artifacts.d.ts";
import TellerJson from "../artifacts/contracts/core/Teller.sol/Teller.json";
import type { Teller$Type } from "../artifacts/contracts/core/Teller.sol/artifacts.d.ts";
import SmartAccountRegistryJson from "../artifacts/contracts/helper/SmartAccountRegistry.sol/SmartAccountRegistry.json";
import type { SmartAccountRegistry$Type } from "../artifacts/contracts/helper/SmartAccountRegistry.sol/artifacts.d.ts";

export type AccountantType = AccountantProviders$Type;
export type BoringVaultType = BoringVault$Type;
export type TellerType = Teller$Type;
export type WithdrawerType = DelayedWithdraw$Type;
export type DistributorType = Distributor$Type;
export type ManagerType = ManagerWithMerkleVerification$Type;
export type SmartAccountRegistryType = SmartAccountRegistry$Type;

export const AccountantAbi = AccountantJson as AccountantType;
export const BoringVaultAbi = BoringVaultJson as BoringVault$Type;
export const TellerAbi = TellerJson as Teller$Type;
export const WithdrawerAbi = WithdrawerJson as DelayedWithdraw$Type;
export const DistributorAbi = DistributorJson as Distributor$Type;
export const ManagerAbi = ManagerJson as ManagerType;
export const SmartAccountRegistryAbi = SmartAccountRegistryJson as SmartAccountRegistryType;
